import { writeFileSync } from 'node:fs';
import { CATALOGUE, SECTIONS } from '../src/lib/conversation/scenarios';
import { runScenario, typesFor, type Scenario, type RunOutcome } from '../src/lib/conversation/harness';

// Writes CONVERSATION_TRANSCRIPTS.md and CONVERSATION_SCOREBOARD.md from one
// run of the catalogue. Both files are generated, never hand-edited: a
// transcript that disagreed with what the engine actually says would be worse
// than no transcript at all.

interface Result {
    scenario: Scenario;
    outcomes: RunOutcome[];
    passed: boolean;
    failures: string[];
}

function run(scenario: Scenario): Result {
    const outcomes = typesFor(scenario).map(t => runScenario(scenario, t));
    const failures = outcomes.flatMap(o => o.steps.flatMap((s, i) =>
        s.failures.map(f => `${o.documentType} step ${i + 1}: ${f}`)));
    return { scenario, outcomes, passed: failures.length === 0, failures };
}

const results = new Map<string, Result>();
for (const s of CATALOGUE) results.set(s.id, run(s));

// ── Transcripts ─────────────────────────────────────────────────────────────

const t: string[] = [
    '# Conversation transcripts',
    '',
    'Generated by `npm run conversation:report`. Do not edit by hand.',
    '',
    'Every scenario in the catalogue, rendered exactly as the engine says it.',
    'Today is fixed at 28 September 2026 so relative dates are reproducible.',
    'The registry id behind each line is shown in brackets, because that is what',
    'the scenario assertions are written against.',
    '',
];

for (const [section, scenarios] of Object.entries(SECTIONS)) {
    t.push(`## ${section}`, '');
    for (const scenario of scenarios) {
        const result = results.get(scenario.id)!;
        for (const outcome of result.outcomes) {
            t.push(`### ${scenario.id} · ${scenario.title} · ${outcome.documentType}`, '');
            t.push(`_${scenario.status}${scenario.note ? ': ' + scenario.note : ''}_`, '');
            t.push('```');
            for (const turn of outcome.conversation.opening) {
                t.push(`M-Track  ${turn.text}   [${turn.copyId}]`);
            }
            for (const step of outcome.steps) {
                const who = step.record.tapped ? 'taps' : 'says';
                t.push(`You ${who}  ${step.record.user}`);
                if (step.record.turns.length === 0) t.push('M-Track  (nothing)');
                for (const turn of step.record.turns) {
                    const opts = turn.options ? `  { ${turn.options.map(o => o.label).join(' | ')} }` : '';
                    t.push(`M-Track  ${turn.text}${opts}   [${turn.copyId}]`);
                }
                for (const f of step.failures) t.push(`   ^ MISSES: ${f}`);
            }
            t.push('```', '');
        }
    }
}
writeFileSync('CONVERSATION_TRANSCRIPTS.md', t.join('\n'));

// ── Scoreboard ──────────────────────────────────────────────────────────────

const total = CATALOGUE.length;
const passing = CATALOGUE.filter(s => results.get(s.id)!.passed).length;

const b: string[] = [
    '# Conversation scoreboard',
    '',
    'Generated by `npm run conversation:report`. Do not edit by hand.',
    '',
    'A scenario may never be marked passing by loosening its assertion. Any change',
    'to an expectation is recorded in the "reason" column of the change log at the',
    'bottom of this file.',
    '',
    `**${passing} of ${total} scenarios pass.**`,
    '',
    '| Section | pass | fail | blocked | decision |',
    '|---|---|---|---|---|',
];

for (const [section, scenarios] of Object.entries(SECTIONS)) {
    const count = (status: string) => scenarios.filter(s => s.status === status).length;
    b.push(`| ${section} | ${count('pass')} | ${count('fail')} | ${count('blocked')} | ${count('decision')} |`);
}

b.push('', '## Every scenario', '', '| ID | Scenario | Status | Note |', '|---|---|---|---|');
for (const [section, scenarios] of Object.entries(SECTIONS)) {
    b.push(`| **${section}** | | | |`);
    for (const s of scenarios) {
        const live = results.get(s.id)!;
        // The recorded status and the live result must agree, or the scoreboard
        // is lying. The suite asserts the same thing.
        const drift = (s.status === 'pass') !== live.passed && s.status !== 'blocked' && s.status !== 'decision'
            ? ' **(drift: recorded status no longer matches the run)**' : '';
        b.push(`| ${s.id} | ${s.title} | ${s.status} | ${(s.note ?? '').replace(/\|/g, '\\|')}${drift} |`);
    }
}

b.push('', '## Expectation change log', '',
    '| Scenario | What changed | Reason |', '|---|---|---|',
    '| B1 | dropped `state({ pending: "input" })` after saving | on_behalf_of correctly walks its purpose question next, so the assertion was wrong about the flow, not about the save. What B1 is about (the line is recorded) is still asserted. |',
    '| B3 | added a second step asserting the reply echoes "lunch" | the original `doesNotAsk` passed while a different question was pending, which made it near-vacuous. |',
    '| C3 | `asks("confirm")` became `asks("description")` | the catalogue says "asks only what is left", and what is left after a date and an amount is the party slot. The original expectation mis-read it. |',
);
writeFileSync('CONVERSATION_SCOREBOARD.md', b.join('\n'));

console.log(`${passing}/${total} scenarios pass. Wrote CONVERSATION_TRANSCRIPTS.md and CONVERSATION_SCOREBOARD.md.`);
